spring.application.name=demo
spring.data.elasticsearch.cluster-name=es01
spring.elasticsearch.host=localhost
spring.elasticsearch.port=9200
spring.elasticsearch.scheme=https


spring.elasticsearch.username=elastic
spring.elasticsearch.password=mIDIoAd*l3vR6fkbN4*=
spring.data.elasticsearch.rest.password=mIDIoAd*l3vR6fkbN4*=
spring.data.elasticsearch.repositories.enabled=true

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
# Define a custom SSL bundle named 'custom-ca'
spring.ssl.bundle.pem.custom-ca.truststore.certificate: classpath:http_ca.crt

logging.level.root=INFO
